### ISSUE TITLE
Update README.md to describe the project and how to run it. 

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#16]
1. Project description
2. How to run it, install requirements.txt
3. How to run it, tailwind server and backend server startup
4. Components list
5. Update the architecture diagrams

**Comment by Khumbolawo** [comment]
![image](https://github.com/user-attachments/assets/0c142060-f43f-4170-808e-2a8d4f2c8e5e)

Tried dumping the schema from sqlite and throwing it on that database  diagram site you used and it doesn't seem to want to work. Will look into that or just do it manually


Update: 

So what I'll try next is to establish a connection to mysql in django, run migrations and try dumping from there instead of sqlite. Does not seem like this site supports SQLite officially.

**Comment by Khumbolawo** [comment]
Done, check out the pull request. Not closing the issue until you approve
